# -*- coding: utf-8 -*-
"""DataManipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saHPlN_s4CmJTTDy5EuGhgxGApnEhPDC
"""

import pandas as pd
import numpy as np
from scipy.signal import butter, filtfilt
import matplotlib.pyplot as plt
'''
butter → designs a Butterworth filter (a smooth, stable filter type with a flat frequency response).

filtfilt → applies it forward and backward so theres zero phase shift (your waveform shape stays aligned in time).
'''

def load_waveform_log(path):
    rows = []
    with open(path, 'r', encoding='latin1') as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            parts = s.split(',')
            if len(parts) != 2:
                continue
            try:
                t = float(parts[0].strip())
                v = float(parts[1].strip())
                rows.append((t, v))
            except ValueError:
                continue
    df = pd.DataFrame(rows, columns=['time', 'value']).dropna()
    df['time'] = pd.to_numeric(df['time'], errors='coerce')
    df['value'] = pd.to_numeric(df['value'], errors='coerce')
    df = df.dropna().reset_index(drop=True)
    return df

def estimate_sampling_rate(df):
    if len(df) < 2:
        return np.nan
    dt = np.diff(df['time'].values)
    median_dt = np.median(dt)
    if median_dt <= 0:
        return np.nan
    return 1.0 / median_dt

def zscore_outlier_filter(df, col='value', z=2.0):
    x = df[col].values.astype(float)
    mu = np.mean(x)
    sd = np.std(x)
    if sd == 0:
        return df.copy(), 0.0
    zscores = (x - mu) / sd
    keep = np.abs(zscores) <= z
    filtered = df.loc[keep].reset_index(drop=True)
    removed_ratio = 1.0 - keep.mean()
    return filtered, removed_ratio
def bandpass_filter(signal, fs, lowcut=0.5, highcut=8, order=4):
    """
    Apply a zero-phase Butterworth band-pass filter to isolate pulse frequencies.
    signal: 1D numpy array or pandas Series
    fs: sampling rate (Hz)
    lowcut: low cutoff frequency in Hz (default 0.5 Hz)
    highcut: high cutoff frequency in Hz (default 8 Hz)
    order: filter steepness (4 = good balance of sharpness/stability)
    """
    nyq = 0.5 * fs                     # Nyquist frequency = half of sample rate
    low = lowcut / nyq                 # Normalize cutoff frequencies (0–1 range)
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')  # Filter coefficients
    filtered = filtfilt(b, a, signal)                # Apply forward & backward
    return filtered

# List of log file paths
files = [
   # '/content/ahmadfootdata.log',
    #'/content/ahmadfootdata2',
    #'/content/ahmadfootdata3',
    'alexfootdata',
    'alexfootdata2',
    'alexfootdata3',   
   # '/content/jorgefootdata',
   # '/content/jorgefootdata2',
    #'/content/jorgefootdata3',
    #'/content/kevinfootdata',
    #'/content/tanfootdata',
   # '/content/tanfootdata2',
   # '/content/tanfootdata3',
]

# Dictionary to store DataFrames
dataframes = {}





# Process each file
for fname in files:
    df = load_waveform_log(fname)
    df, removed_ratio = zscore_outlier_filter(df)
    fs = estimate_sampling_rate(df)
    print(f"{fname} → {len(df)} rows, ~{fs:.2f} Hz sampling rate, removed {removed_ratio*100:.1f}% outliers.")
    
     # 🩺 Apply band-pass filter if we know the sample rate
    if fs and not np.isnan(fs):
        df['filtered'] = bandpass_filter(df['value'], fs)

        # quick visualization
        plt.figure(figsize=(10,4))
        plt.plot(df['time'], df['value'], alpha=0.4, label='Raw')
        plt.plot(df['time'], df['filtered'], label='Filtered (0.5–8 Hz)')
        plt.title(f"Band-pass filtered waveform: {fname.split('/')[-1]}")
        plt.xlabel('Time (s)')
        plt.ylabel('Sensor Value')
        plt.legend()
        plt.tight_layout()
        plt.show()

    # Store each DataFrame in the dictionary
    file_name = fname.split('/')[-1]
    dataframes[file_name] = df

    # Print some debug information
    print(f"Processed DataFrame '{file_name}':")
    print(df.head())  # Print first few rows to inspect

# Print first few rows of each DataFrame to verify
for file_name, df in dataframes.items():
    print(f"\nFirst few rows of DataFrame '{file_name}':")
    print(df.head())

"""Step 2: Plotting the Raw Data
Let's plot the raw data for each file to visualize the waveforms.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Plotting function
def plot_data(df, file_name):
    time = df['time']
    points = df['point']

    plt.figure(figsize=(15, 5))
    plt.plot(time, points, label='Original Data')
    plt.title(f'Original Data for {file_name}')
    plt.xlabel('Time')
    plt.ylabel('Sensor Value')
    plt.legend()
    plt.tight_layout()
    plt.show()
# Assuming `dataframes` contains actual data as dictionaries of lists
for file_name, content in dataframes.items():
    data = content.values.tolist()
    df = pd.DataFrame(data, columns=['time', 'point'])
    plot_data(df, file_name)

"""Step 3: Cleaning the Data using Fourier Transform"""

# Function to compute and plot the Fourier transform
def plot_fourier_transform(df, title, cutoff_freq=.1):
    #Discretize time t
    t0=-100.
    dt=0.001
    t=np.arange(t0,-t0,dt)
    #Define function
    f=1./(t**2+1.)

    #Compute Fourier transform by numpy's FFT function
    g=np.fft.fft(f)
    #frequency normalization factor is 2*np.pi/dt
    w = np.fft.fftfreq(f.size)*2*np.pi/dt



def chatgpt_function_plot_fourier_transform(df, title, cutoff_freq=.1):
    # Extract the 'point' values
    y = df['point']

    # Compute the Fourier transform
    fft_values = np.fft.fft(y)
    print("first ten values", fft_values[:10])
    fft_freq = np.fft.fftfreq(100)

    # Apply cutoff frequency
    # fft_values_filtered = np.where(np.abs(fft_freq) > cutoff_freq, 0, fft_values)

    # Plot the original signal
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    plt.plot(df['time'], y, label='Original Signal')
    plt.title(f'Time Domain Signal - {title}')
    plt.xlabel('Time')
    plt.ylabel('Point Value')
    plt.legend()

    # Plot the Fourier transform
    plt.subplot(1, 2, 2)
    plt.plot(fft_freq, fft_values[:100], label='Original Fourier Transform')
    # plt.plot(fft_freq, np.abs(fft_values), label='Original Fourier Transform')
    # plt.plot(fft_freq, np.abs(fft_values_filtered), label='Filtered Fourier Transform')
    plt.title(f'Frequency Domain Signal - {title}')
    plt.xlabel('Frequency')
    plt.ylabel('Amplitude')
    plt.legend()

    plt.tight_layout()
    plt.show()



def plot_fourier_transform(df, title):
    # Extract the 'point' values
    y = df['point']
    N = len(y)

    # Compute the Fourier transform
    fft_values = np.fft.fft(y)
    SAMPLE_RATE = 1 / (df['time'].iloc[1] - df['time'].iloc[0])  # Calculate the sample rate based on time interval
    fft_freq = np.fft.fftfreq(N, 1 / SAMPLE_RATE)

    # Only plot the positive half of the spectrum
    idx = np.arange(N // 2)

    # Plot the original signal
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    plt.plot(df['time'], y, label='Original Signal')
    plt.title(f'Time Domain Signal - {title}')
    plt.xlabel('Time')
    plt.ylabel('Point Value')
    plt.legend()

    # Plot the Fourier transform (magnitude)
    plt.subplot(1, 2, 2)
    plt.plot(fft_freq[idx], np.abs(fft_values[idx]), label='Fourier Transform')
    plt.title(f'Frequency Domain Signal - {title}')
    plt.xlabel('Frequency (Hz)')
    plt.ylabel('Amplitude')
    plt.legend()

    plt.tight_layout()
    plt.show()

# Plot Fourier transform for each DataFrame
for file_name, df in dataframes.items():
    plot_fourier_transform(df, file_name)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.fft import fft, ifft, fftfreq
# Import the required packages
import numpy as np
from scipy.fft import fft, rfft
from scipy.fft import fftfreq, rfftfreq
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt
# %matplotlib inline
# Define cutoff frequency and sampling rate
cutoff_frequency = 50  # Example cutoff frequency in Hz
sampling_rate = 1000
# Function to clean and process data with cutoff frequency
def clean_data(df, cutoff_frequency, sampling_rate):
    # Ensure 'point' column is numeric and handle NaN values
    if 'point' in df.columns:
        print(f"Processing DataFrame with {len(df)} rows.")
        df['point'] = pd.to_numeric(df['point'], errors='coerce')
        df = df.dropna(subset=['point'])
        df['point'] = df['point'].astype(float)

        # Remove DC component
        df['point'] = df['point'] - df['point'].mean()

        # Perform FFT
        N = len(df['point'])
        fft_result = fft(df['point'])

        # Frequency array
        freqs = fftfreq(N, d=1/sampling_rate)

        # Apply cutoff frequency filter
        fft_result[np.abs(freqs) > cutoff_frequency] = 0

        return fft_result
    else:
        print(f"'point' column not found in dataframe for {file_name}")
        return None

# Example usage
 # Example sampling rate in Hz

# Print versions of packages
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")

# Check content of dataframes dictionary
print(f"Dataframes keys: {dataframes.keys()}")

# Process data
cleaned_data = {}
for file_name, df in dataframes.items():
    print(f"Processing file: {file_name}")
    fft_result = clean_data(df, cutoff_frequency, sampling_rate)
    if fft_result is not None:
        cleaned_data[file_name] = fft_result

# Plot cleaned data or FFT results
for file_name, fft_result in cleaned_data.items():
    plt.figure()
    plt.plot(np.abs(fft_result))
    plt.title(f'FFT Result for {file_name}')
    plt.xlabel('Frequency')
    plt.ylabel('Amplitude')
    plt.show()